//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DEFAULT_INFECTION_DRAW {
            get {
                return ((int)(this["DEFAULT_INFECTION_DRAW"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int MAX_DISEASE_CUBES {
            get {
                return ((int)(this["MAX_DISEASE_CUBES"]));
            }
            set {
                this["MAX_DISEASE_CUBES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int MAX_OUTBREAK_COUNT {
            get {
                return ((int)(this["MAX_OUTBREAK_COUNT"]));
            }
            set {
                this["MAX_OUTBREAK_COUNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Atlanta")]
        public string DEFAULT_STARTING_LOCATION {
            get {
                return ((string)(this["DEFAULT_STARTING_LOCATION"]));
            }
            set {
                this["DEFAULT_STARTING_LOCATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MAX_INPUT_LENGTH {
            get {
                return ((int)(this["MAX_INPUT_LENGTH"]));
            }
            set {
                this["MAX_INPUT_LENGTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DEFAULT_PLAYER_ACTIONS {
            get {
                return ((int)(this["DEFAULT_PLAYER_ACTIONS"]));
            }
            set {
                this["DEFAULT_PLAYER_ACTIONS"] = value;
            }
        }
    }
}
